### ISSUE TITLE
iOS 知乎APP 去广告规则失效了。

### ISSUE THREAD

**Issue by Fezreal** [ConnersHua/Profiles#11]
// Zhihu
DOMAIN-SUFFIX,sugar.zhihu.com,REJECT
DOMAIN-SUFFIX,zhihu-analytics.zhihu.com,REJECT
DOMAIN-SUFFIX,zhihu-web-analytics.zhihu.com,REJECT
DOMAIN-SUFFIX,zhstatic.zhihu.com,REJECT

知乎近日更新了一次， 加入了很多广告。。。 希望能更新一下。

**Comment by ConnersHua** [comment]
好了
