### ISSUE TITLE
Surge 3 專業版開啟 MITM 後無法打開知乎

### ISSUE THREAD

**Issue by Snapsugar** [ConnersHua/Profiles#111]
在使用Surge 3 專業版本並且開啟 MITM 後，無法打開知乎網頁，提示 Unable to establish a secure connection.

**Comment by ConnersHua** [comment]
https://github.com/ConnersHua/Profiles/wiki/%E5%85%B3%E4%BA%8E%E5%8E%BB%E5%B9%BF%E5%91%8A

**Comment by Snapsugar** [comment]
你好，已經安裝並且信任證書

**Comment by ConnersHua** [comment]
删除掉已安装的描述文件然后重新安装信任

**Comment by Snapsugar** [comment]
你好，已經解決，感謝
