### ISSUE TITLE
投稿：知乎移动版网页的app中打开变成展开阅读全文

### ISSUE THREAD

**Issue by xream** [ConnersHua/Profiles#113]
原理 zhihuvvv.com

^https?:\/\/(www.)?zhihu\.com header-del Referer
^https?:\/\/(www.)?zhihu\.com header-add Referer cache.baidu.com,cache.so.com,cache.sogou.com,cache.soso.com

**Comment by ConnersHua** [comment]
感谢

**Comment by shensuv** [comment]
这个这段时间好像已经失效了，不知道除了请求桌面端还有什么办法能够访问。
