### ISSUE TITLE
投稿微信公众号去广告

### ISSUE THREAD

**Issue by gkeyes** [ConnersHua/Profiles#115]
^https:\/\/mp.weixin.qq.com\/mp\/(getappmsgad|appmsgreport|ad_repor|advertisement|readtemplate).* - reject
^https?:\/\/wxsnsdythumb.wxs.qq.com\/\d+\/\d+\/snsvideodownload.* - reject
^https?:\/\/.*(/)?adsmind.tc.qq.com\/vcloud.tc.qq.com\/.* - reject
^https?:\/\/lf.snssdk.com\/api\/ad\/union\/show_event.* - reject
^https?:\/\/wxsnsdy.wxs.qq.com\/\d+\/\d+\/snsdyvideodownload.* - reject
^https?:\/\/.+\.beacon\.qq\.com\/analytics\/upload.* - reject

Host=*.beacon.qq.com, *.wxs.qq.com, mp.weixin.qq.com, *.adsmind.tc.qq.com, lf.snssdk.com

**Comment by gkeyes** [comment]
之前自己弄的过滤规则，不知道有没有跟现有的重复，不过我一直可以过滤微信公众号里的广告

**Comment by ConnersHua** [comment]
感谢反馈，已结合
