### ISSUE TITLE
CH大佬能不能帮忙搞搞Kitsunebi的规则？

### ISSUE THREAD

**Issue by LaurenceSamael** [ConnersHua/Profiles#116]
最近发现YouTube开始流氓了，以前播一次广告只有一个，现在连着播两个，跟某酷偷师了非常反感。
请求大佬能否做个可以屏蔽YouTube app端的kitsunebi规则呢？
非常感谢

**Comment by ConnersHua** [comment]
感谢反馈，这个 Kits 做不了
