### ISSUE TITLE
建议Surge3Pro里面把 rewrite 替换成URL-REGEX，并独立成一个List

### ISSUE THREAD

**Issue by maxduke** [ConnersHua/Profiles#122]
3.8 后URL-REGEX支持MitM了

**Comment by ConnersHua** [comment]
有两个问题

1. 涉及到 MitM hostname 还是要手动更新，Rewrite 有了 hsotname 没有也用不了而且目前大多都要 MitM 配合
2. 维护困难

**Comment by ConnersHua** [comment]
感谢反馈已集成进 Advertising.list
