### ISSUE TITLE
用了surge3的配置u2b打不开了。。。。

### ISSUE THREAD

**Issue by fuzhouxxdong** [ConnersHua/Profiles#126]
如题

**Comment by fuzhouxxdong** [comment]
![photo_2019-07-02_14-45-20](https://user-images.githubusercontent.com/5198378/60489912-10309880-9cd8-11e9-8e62-567d9e3ba120.jpg)

**Comment by ConnersHua** [comment]
弄证书了？

**Comment by fuzhouxxdong** [comment]
弄了证书， 是不需要证书吗





 
发件人： Conners Hua
发送时间： 2019-07-02 14:47
收件人： ConnersHua/Profiles
抄送： 1; Author
主题： Re: [ConnersHua/Profiles] 用了surge3的配置u2b打不开了。。。。 (#126)
弄证书了？

**Comment by ConnersHua** [comment]
肯定是没信任，看 Wiki

**Comment by fuzhouxxdong** [comment]
哈哈， 我的锅。。。可以了
