### ISSUE TITLE
Clash for Windows下无法连接Windows store

### ISSUE THREAD

**Issue by chenxinyucn** [ConnersHua/Profiles#128]
1. 不论global/rule/direct, Windows store及旗下国内应用，如东方财富均无法连接网络
2.  OneDrive for business在rule模式下无法走节点，global可以。因OneDrive for business在高峰期会掉速，望加入rule规则当中

**Comment by ConnersHua** [comment]
https://github.com/Fndroid/clash_for_windows_pkg/wiki/UWP%E5%BA%94%E7%94%A8%E8%81%94%E7%BD%91

**Comment by chenxinyucn** [comment]
谢谢，第一个问题了解原理了！OneDrive for business还是希望能加入默认代理的规则，谢谢！
