### ISSUE TITLE
希望将onedrive for business加入默认代理列表

### ISSUE THREAD

**Issue by ssacpklnm** [ConnersHua/Profiles#132]
如题，微软的各个服务器虽然在国内可以访问，但是速度去没有很快，在onedrive的体现上尤为明显，毕竟需要高带宽，希望将onedrive for business加入默认代理列表，据我所知主要是sharepoint.com这个域名，谢谢

**Comment by ConnersHua** [comment]
已移除直连，GeoIP 处理非 CN IP 走代理
