### ISSUE TITLE
Quantumult - Pro.conf 建议添加YouTube Music规则

### ISSUE THREAD

**Issue by van7ish** [ConnersHua/Profiles#143]
因为香港和台湾地区，以及其他一些国家地区，没法使用YouTube Music。
另外，日区DAZN流媒体对IP限制严格，建议完善一下DAZN的规则。

**Comment by ConnersHua** [comment]
YouTube Music 的 Streaming 和 Youtube 一样分不开，DAZN 没账号测试只能加了个主域名你看看你不能用吧

**Comment by ConnersHua** [comment]
G.L.H.F
