### ISSUE TITLE
Clash - Pro 建议删除domesticmedia部分

### ISSUE THREAD

**Issue by zhuohan** [ConnersHua/Profiles#145]
日常使用中bilibili的解锁脚本非常的卡，经查询，发现upos-hz-mirrorakam.akamaized.net走的是domesticmedia直连[https://github.com/ConnersHua/Profiles/blob/4f07f50c3f6a46174b4392eb06314d0847d31937/Clash/Pro.yaml#L541](url)

经以下链接和实测得出结论，upos-hz-mirrorakam.akamaized.net用了一家美国的cdn，在大陆大部分地区会解析到美国，而不是香港和台湾。在北方3家服务器测试ping值均为180ms，默认直连并没有意义[https://github.com/ipcjs/bilibili-helper/issues/401](url)

除upos-hz-mirrorakam.akamaized.net之外，domesticmedia的其他规则，在配置文件其他地方都有重复设置，因此domesticmedia部分可以删除

最后经本人实测，删掉domesticmedia之后，bilibili访问速度加快

**Comment by ConnersHua** [comment]
默认就是不代理限区，当需要看限制区 DomesticMedia 就改成代理节点这才是 DomesticMedia 的作用

**Comment by zhuohan** [comment]
> 默认就是不代理限区，当需要看限制区 DomesticMedia 就改成代理节点这才是 DomesticMedia 的作用

明白了
