### ISSUE TITLE
MitM 状态失败

### ISSUE THREAD

**Issue by touzi** [ConnersHua/Profiles#146]
MitM 解析 很多域名都显示状态为 失败 . 比如域名 api.weibo.cn

**Comment by touzi** [comment]
然后微博国际版还会造成一个 sdk.e.qq.com:443 不停的循环请求很长时间才停止

**Comment by ConnersHua** [comment]
> MitM 解析 很多域名都显示状态为 失败 . 比如域名 api.weibo.cn

1.「用于 TCP 连接」关闭
2.证书安装
3.证书信任

**Comment by ConnersHua** [comment]
> 然后微博国际版还会造成一个 sdk.e.qq.com:443 不停的循环请求很长时间才停止

傻逼国际版每次开屏都调广告

**Comment by touzi** [comment]
「跳过服务器端证书」开启, 「用于 TCP 连接」关闭 然后 生成新的证书, 安装新的证书, 证书信任. 
结果还是不行

**Comment by touzi** [comment]
无意中发现 sdkapp.uve.weibo.com 也是失败的

**Comment by ConnersHua** [comment]
证书怎么信任的？

**Comment by touzi** [comment]
通用>描述文件与设备管理>信任

**Comment by ConnersHua** [comment]
意料之中，这不叫信任

**Comment by touzi** [comment]
啊. 怎么操作

**Comment by touzi** [comment]
找到了, 谢谢

**Comment by touzi** [comment]
信任证书的方法: 通用>关于>打勾
