### ISSUE TITLE
安卓FCM直连请求

### ISSUE THREAD

**Issue by Upapanow** [ConnersHua/Profiles#152]
请求直连 mtalk.google.com
否则在安卓的Kits下会有连接超时错误，导致fcm退出无法收取推送

**Comment by ConnersHua** [comment]
感谢反馈，已处理。

**Comment by Upapanow** [comment]
经测试，Fcm的问题依然存在
在kitsunebi中使用ssr，全局规则为120秒断一次（这是ssr本身的问题），使用神机规则59秒断一次
使用v2，全局规则，不会断线，使用神机规则59秒断一次。
不使用任何代理软件则不会断线。
在使用神机规则时kitsunebi代理日志显示mtalk.google.com为direct，但Fcm依旧59秒必断

**Comment by ConnersHua** [comment]
这个问题邮件下作者吧，另外在v2里使用ssr是什么鬼

**Comment by Upapanow** [comment]
邮件给kitsunebi的作者吗？我看issue版面太多没有处理了，估计在咕咕，不一定会解决……

**Comment by ConnersHua** [comment]
嗯，邮件会好点
