### ISSUE TITLE
Clash - BacktoCN DNS问题

### ISSUE THREAD

**Issue by zhuohan** [ConnersHua/Profiles#153]
在使用clash backtocn时，google maps打不开，看log是dns解析到了中国的ip，走了geoip回国。在改了clash dns到1.1.1.1后恢复可用，我看kitsunebi里有local和remote dns的区别，那clash这边是不是默认也应该是国外的dns？

**Comment by ConnersHua** [comment]
回国不设 DNS 也可以，将 dns 部分删掉吧
