### ISSUE TITLE
Surge 3 無法打開京東

### ISSUE THREAD

**Issue by Snapsugar** [ConnersHua/Profiles#154]
使用 Surge 3 的規則，開啟 MitM 之後，在京東 App 中搜索商品一直加載中，有時甚至提示與網絡斷開連結。關閉 MitM 之後，一切正常

**Comment by ConnersHua** [comment]
证书没信任，看 README

**Comment by Snapsugar** [comment]
已經信任過了

**Comment by ConnersHua** [comment]
信任和最近请求截图

**Comment by Snapsugar** [comment]
![5967C4FC-071D-42AA-81B3-E353C2A3C809](https://user-images.githubusercontent.com/30021422/63635765-09e7e880-c699-11e9-8074-7b1acfd3e213.jpeg)
![867AE53B-C91E-4587-AECA-BFECF045F4A0](https://user-images.githubusercontent.com/30021422/63635766-0a807f00-c699-11e9-93c1-f4ab0cda39e9.png)

**Comment by ConnersHua** [comment]
打开「抓取流量」后打开京东并搜索，然后在保存的抓取数据里查看「api.m.jd.com」的状态

**Comment by Snapsugar** [comment]
你好，抓取的流量中並沒有「api.m.jd.com」的請求

**Comment by Snapsugar** [comment]
「api.m.jd.com」的請求在關閉 MitM 後，才在抓取的流量中找到

**Comment by Snapsugar** [comment]
![559E6DD4-5204-4E2E-BA79-9A517D6F178A](https://user-images.githubusercontent.com/30021422/63636015-1c175600-c69c-11e9-9319-897dc1d61014.png)
關閉 MitM 之後，抓取的數據才顯示連接成功

**Comment by ConnersHua** [comment]
不管开不开都应该有记录才对，疑似 Bug，联系 Surge 作者吧

**Comment by Snapsugar** [comment]
目前系統是 iOS 13 Public Beta，升級之後出現的情況

**Comment by Snapsugar** [comment]
您好，在使用 TestFlight 版本後，該問題已經得到解決
