### ISSUE TITLE
Surge3下的Advertising.list规则导致无法使用youtube video和youtube music

### ISSUE THREAD

**Issue by oxoxoxox** [ConnersHua/Profiles#160]
iOS和macOS下都有同样的问题，视频无法加载，音乐也无法加载
查Surge的log发现是 URL-REGEX,^https?:\/\/.+\.googlevideo\.com\/.+ctier 这条规则导致的
麻烦修复一下

**Comment by ConnersHua** [comment]
hostname 怎么设置的

**Comment by oxoxoxox** [comment]
> hostname 怎么设置的

加入了 *.googlevideo.com, *.youtube.com

**Comment by ConnersHua** [comment]
你没看 README，另外注释有提到，macOS不要开广告拦截

**Comment by oxoxoxox** [comment]
> 你没看 README，另外注释有提到，macOS不要开广告拦截

呃，好吧，这个plist我已经用了很久了，已经很久没有上来看新版本的readme了
