### ISSUE TITLE
苹果地图数据使用问题

### ISSUE THREAD

**Issue by Scorpion4286** [ConnersHua/Profiles#163]
使用Clash Pro版规则。
在Apple组使用DRIECT，Final Proxy条件下。
(Apple News那些也都注解掉了。)

iPad自带的苹果地图只有TOMTOM的数据，没有高德。
但在iPhone上是好的，高德的数据也在。

现在苹果是拿什么方法判断使用地图数据的啊？
在保持Final Proxy的情况下，需要添加哪些规则才能用上高德的数据呢？

**Comment by Scorpion4286** [comment]
那条也删掉了，还设置了Apple的DOMAIN-KEYWORD为DIRECT，还是不行。

**Comment by ConnersHua** [comment]
直接删了（iOS）地图，不开代理下重装再开，把缓存弄掉

**Comment by Scorpion4286** [comment]
我试过了，不是缓存的问题，通过抓包发现，每次打开地图，都会向一家叫Akamai的CDN公司发包(IP不固定，没找到DNS解析记录)。一旦这个流量MATCH到了Proxy，就只有TOMTOM的数据了。

**Comment by Scorpion4286** [comment]
查到了地址段，经测试，以下两条配合清除缓存可解。
```
- DOMAIN-SUFFIX,akamaiedge.net,DIRECT
- IP-CIDR,23.2.139.0/25,DIRECT
```

**Comment by Loyalsoldier** [comment]
```
- DOMAIN-SUFFIX,akamaiedge.net,DIRECT
```

这条规则打击面太广。

```
- IP-CIDR,23.2.139.0/25,DIRECT
```

这条规则的 IP 段只是中国电信的解析结果吧。

个人觉得针对 iPad 地图 app 的 User-Agent 来弄比较妥当吧
