### ISSUE TITLE
开启 Quantumult X Rewrite 后豆瓣客户端无法加载图片

### ISSUE THREAD

**Issue by Hayxi** [ConnersHua/Profiles#168]

**Comment by ConnersHua** [comment]
检查证书是否信任

**Comment by Hayxi** [comment]
已信任，关掉可加载。网页无影响。

**Comment by ConnersHua** [comment]
信任设置、豆瓣无法加载图片位置、Quantumult X 网络活动 img*.doubanio.com 相关记录截图

**Comment by Hayxi** [comment]
![IMG_0231](https://user-images.githubusercontent.com/17973240/65382932-5417c480-dd40-11e9-8e8b-c1d5c6239137.png)
![IMG_0232](https://user-images.githubusercontent.com/17973240/65382935-5bd76900-dd40-11e9-9200-45cbd5599114.png)
![IMG_0235](https://user-images.githubusercontent.com/17973240/65382936-5ed25980-dd40-11e9-96a6-ef0b8285e210.png)

**Comment by ConnersHua** [comment]
有数据的不知道为什么没显示

**Comment by Hayxi** [comment]
似乎只要开启 `img*.doubanio.com` 的解密就无法显示

**Comment by ConnersHua** [comment]
G.L.H.F

**Comment by Fancnia** [comment]
skip_validating_cert = false
force_sni_domain_name = false

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hayxi** [comment]
已解决，十分感谢。
