### ISSUE TITLE
建议添加ClashRA的shadowsockr模板

### ISSUE THREAD

**Issue by panda-mute** [ConnersHua/Profiles#175]
# ShadowsocksR
- cipher: xxx
  name: "xxx"
  obfs: tls1.2_ticket_auth
  obfsparam: ''
  password: xxxx
  port: 'xxx'
  protocol: auth_chain_a
  protocolparam: ''
  server: www.example.com
  type: ssr

**Comment by ConnersHua** [comment]
拒绝。
