### ISSUE TITLE
威锋app ^https?:\/\/(api|gapi)\.feng\.com\/v\d\/advertisement\/规则有问题

### ISSUE THREAD

**Issue by eHpo1** [ConnersHua/Profiles#183]
这个规则会导致首页上面轮播图片看不见，屏蔽开屏广告用这个规则就行
,^https?:\/\/api\.feng\.com.*Claunch_screen%5D&project=weiphoforumne2$

**Comment by eHpo1** [comment]
Claunch_screen是关键词

**Comment by ConnersHua** [comment]
G.L.H.F
