### ISSUE TITLE
Add request:Apple Music

### ISSUE THREAD

**Issue by yogaskung** [ConnersHua/Profiles#2]
Please add these lines:
`DOMAIN-SUFFIX,audio.itunes.apple.com,PROXY,force-remote-dns
DOMAIN-SUFFIX,streamingaudio.itunes.apple.com,PROXY,force-remote-dns`
Reason:It’s too slow to download and listen to Apple Music

**Comment by ConnersHua** [comment]
Thanks for your feedback, I will consider it
