### ISSUE TITLE
Quanmult 重复提示信任证书问题

### ISSUE THREAD

**Issue by ccccatz** [ConnersHua/Profiles#201]
手机型号：iPhone 7 
系统 : 13.1.2
软件：Quantumult 

严格按照教程操作(在另一台iOS 12.3.1上已成功)，信任了证书，但每次在Quantumult上尝试打开代理都提示“根证书已安装，但未信任..."。

重启机器，重新安装证书都不成功。 是因为系统的原因吗？

![IMG_4320](https://user-images.githubusercontent.com/55619226/68124873-4f534c80-ff4b-11e9-98a7-9ac71a326c93.JPG)
![IMG_4321](https://user-images.githubusercontent.com/55619226/68124875-524e3d00-ff4b-11e9-971a-586d242d7b65.JPG)

**Comment by ConnersHua** [comment]
删除 Quantumult 重装试试，还不行邮件联系作者吧

**Comment by ccccatz** [comment]
> 删除 Quantumult 重装试试，还不行邮件联系作者吧

谢大佬，很神奇，重装了Quantumult，问题解决 。 

感谢。 🙏
