### ISSUE TITLE
bilibili默认走proxy？

### ISSUE THREAD

**Issue by Creolophus** [ConnersHua/Profiles#208]
# (HKMTMedia)
# > bilibili
DOMAIN-SUFFIX,bilibili.com,⚠️bilibili港澳台专用节点(没有就选DIRECT)
DOMAIN,upos-hz-mirrorakam.akamaized.net,⚠️bilibili港澳台专用节点(没有就选DIRECT)
# > 愛奇藝台灣站
DOMAIN-SUFFIX,iqiyi.com,⚠️愛奇藝台灣站专用节点(没有就选DIRECT),force-remote-dns

这里bilibili默认走proxy？我导入规则后iPhone上打开bilibili全走的proxy。。。

**Comment by ConnersHua** [comment]
那你在订阅的时候个性化为什么不选择 DIRECT？不是写着「没有就选DIRECT」么

**Comment by Creolophus** [comment]
好吧，不太会用quan，才看到规则里有个个性化选项
