### ISSUE TITLE
Netflix uwp 版本受到 BacktoCN.conf 规则干扰

### ISSUE THREAD

**Issue by iamfuhui** [ConnersHua/Profiles#213]
查看 log 发现
Netflix uwp 启动后，会访问 checkappexec.microsoft.com activities.microsoft.com，
目前的情况是，BacktoCN 规则 走了回国路线。
引起 Netflix uwp 播放卡住。

手动删除了 BacktoCN 规则中的，*.microsoft.com 相关后可以正常播放。

起因：chrome 播放一直没有问题，换 uwp 和 edge 均出现问题。

**Comment by ConnersHua** [comment]
BacktoCN.conf 中没有 DOMAIN-SUFFIX,microsoft.com 啊

**Comment by iamfuhui** [comment]
抱歉... 我 引用了 China.list 作为 BacktoCN

因为有些网站 China.list 没涵盖。

**Comment by ConnersHua** [comment]
主要是哪些网站有问题？不建议回国中使用 China.list

**Comment by iamfuhui** [comment]
我的确在墙外。

并且用了新加坡节点解锁 Netflix，这样导致了问题。

China.list 主要是考虑 淘宝 的访问。

否则切换到海外站的淘宝。

**Comment by ConnersHua** [comment]
淘宝的话用
```
DOMAIN-SUFFIX,taobao
```
应该能解决，如果还不行加上
```
DOMAIN-SUFFIX,alicdn.com
```

**Comment by iamfuhui** [comment]
多谢！
