### ISSUE TITLE
用了特别版之后影响了siri

### ISSUE THREAD

**Issue by Leo2016** [ConnersHua/Profiles#22]

**Comment by ConnersHua** [comment]
未对 Siri 相关做代理，可尝试将 DNS 改成 system

**Comment by Leo2016** [comment]
iOS，4G网络，也能修改DNS？

**Comment by ConnersHua** [comment]
可以，我规则中 DNS 覆写成公共 DNS，你可以看下 DNS 结果中是哪个 DNS 把 Siri 解析出问题了，或者直接改成 system 使用运营商指定 DNS

**Comment by Leo2016** [comment]
好的，感谢，我去试试看。感谢大佬
