### ISSUE TITLE
添加Protonmail相关域名

### ISSUE THREAD

**Issue by Mosney** [ConnersHua/Profiles#225]
国内直连速度缓慢，可以考虑加到代理规则内，以下是目前发现的相关域名后缀
```
protonmail.com
protonmail.ch
```
ref:https://zh.wikipedia.org/zh-hans/ProtonMail

**Comment by ConnersHua** [comment]
感谢建议，请自行添加吧，本项目即将终止

**Comment by Mosney** [comment]
好的 其实我本地也维护了一份自己用的clash规则 还有一些域名打算有时间再开个PR提交 不过还是感谢你的付出
