### ISSUE TITLE
Bilibili 规则问题

### ISSUE THREAD

**Issue by lizongzeshunshun** [ConnersHua/Profiles#226]
https://github.com/ConnersHua/Profiles/blob/db7788a50d5c971d1cb16a240d945365724f1580/Clash/Pro.yaml#L679

https://github.com/ConnersHua/Profiles/blob/db7788a50d5c971d1cb16a240d945365724f1580/Clash/Pro.yaml#L1266

这两处分别对 Bilibili 做了不同处理，不知是什么原因？

正常使用情况下因为第一处优先命中，导致日常使用极慢。

**Comment by ConnersHua** [comment]
HKMTMedia 用于解锁港澳台限定内容，日常选 DIRECT 策略，如果你不看港澳台限定直接删掉相关策略组和策略

**Comment by lizongzeshunshun** [comment]
了解。谢谢。
