### ISSUE TITLE
请问可以用在pc版本的v2rayN版本吗？

### ISSUE THREAD

**Issue by zasl** [ConnersHua/Profiles#25]
如果可以能告知一下方法吗？

**Comment by ConnersHua** [comment]
如果是使用我的自定义配置，首先需要修改一下内容，将「inbound」内容也就是
`"inbound" : {
    "domainOverride" : [
      "http",
      "tls"
    ],
    "port" : 1086,
    "listen" : "127.0.0.1",
    "protocol" : "http",
    "settings" : {
      "auth" : "noauth",
      "udp" : true
    }
  }`
修改为
`"inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    }
  }`
然后在 v2rayN 中的「服务器」选择「添加自定义配置服务器」，将刚才添加的「Custom」设为「活动服务器」后，右下角托盘图标的设置中的「Http代理模式」选择「开启Http代理，并自动配置代理服务器(全局模式)」

**Comment by ConnersHua** [comment]
另外，Windows 中的全局也全局不到哪去，不建议这么用
