### ISSUE TITLE
关于Google Voice呼出和呼入的规则问题

### ISSUE THREAD

**Issue by Nyim1s** [ConnersHua/Profiles#254]
呼出：
增加HOST-SUFFIX：voice.telephony.goog（就是goog，不是google）策略到proxy可以让Google Voice正常呼出。
但是仅对quanx有效，对quan无效。
在quanx的”网络活动“中可以看到GV客户端呼出时连接voice.telephony.goog和对应的IP，且可以正常听到“拨通音”在响。
但是quan的“网络活动”中就只能看到域名对应的IP（未显示域名），且将voice.telephony.goog添加到规则里，也无效。

呼入：
经过观察发现GV客户端在收到呼入请求时，会连接mtalk.google.com，但在Unbreak.list里看到mtalk.google.com的策略为Direct，不知是何用意？

**Comment by ConnersHua** [comment]
mtalk.google.com 是 FCM，有未墙 IP

Quantumult 不可用盲猜是 UDP 未代理，尝试「UDP 转发」设置一个代理进行测试

**Comment by ConnersHua** [comment]
如果是白名单模式才能用，将以下规则加到末尾 GeoIP 规则之前

```
# > Google
IP-CIDR,35.190.247.0/24,PROXY
IP-CIDR,64.233.160.0/19,PROXY
IP-CIDR,66.102.0.0/20,PROXY
IP-CIDR,66.249.80.0/20,PROXY
IP-CIDR,72.14.192.0/18,PROXY
IP-CIDR,74.125.0.0/16,PROXY
IP-CIDR,108.177.8.0/21,PROXY
IP-CIDR,172.217.0.0/16,PROXY
IP-CIDR,173.194.0.0/16,PROXY
IP-CIDR,209.85.128.0/17,PROXY
IP-CIDR,216.58.192.0/19,PROXY
IP-CIDR,216.239.32.0/19,PROXY
```

**Comment by Nyim1s** [comment]
谢谢！USER-AGENT的话不知道是不是也可以，可惜我不知道Google Voice客户端的名字。。

**Comment by ConnersHua** [comment]
请求不一定带 User-Agent，可以自行尝试添加两项：

com.google.GVDialer*

VoiceApp*

**Comment by Nyim1s** [comment]
谢谢
