### ISSUE TITLE
小疑惑

### ISSUE THREAD

**Issue by zskein** [ConnersHua/Profiles#26]
Kitsunebi访问Instagram客户端 好慢、好慢， 有时候能加载页面，有时候不能加载页面。感觉应该不是规则的问题，但又找不到具体原因所在，猜测是IG客户端的通信服务器问题吧 ， 只好删除IG客户端使用网页版，不确定问题所在，所以就反馈一下。

**Comment by ConnersHua** [comment]
这个我也收到过反馈，还是和 Kitsunebi 作者反馈下吧，我这没法解决
