### ISSUE TITLE
专业版问题

### ISSUE THREAD

**Issue by irenz** [ConnersHua/Profiles#29]
亲，使用专业版后为Google一部分应用无法使用，比如G+/YouTu/hangouts，但文档这些又能用好像，为什么呢，标准版倒是没有问题。ShadowPro.conf这个，是我设置问题还是文件问题呢？

**Comment by irenz** [comment]
好纠结啊

**Comment by irenz** [comment]
好像也不是全部，现在试下来是YouTube/G+/还有个什么，但云盘文档这些又没问题

**Comment by ConnersHua** [comment]
你是在使用 Shadowrocket 最新版？专业版规则安装并且信任了证书是吧？

**Comment by irenz** [comment]
嗯，是的，证书也安装信任了

**Comment by ConnersHua** [comment]
这应该是个 Bug，因为 Youtube 和 GoogleAPI 的域名在 MitM 的 hostname 中导致的，和作者邮件反馈后得到的暂时解决方法是进入设置将「HTTPS 解密」功能关闭等待作者更新，如果你是 TestFlight 可以回退到 2.1.22(638)  也可以解决此问题。

**Comment by irenz** [comment]
呃，为什么我设置里没有HTTPS解密的选项。。。。
还有就是，我使用其他配置文件倒是没这个问题，只有你的PRO会出现

**Comment by ConnersHua** [comment]
点击规则名选择「编辑配置」后可看到「HTTPS 解密」选项，另外你还使用了哪些配置文件？

**Comment by irenz** [comment]
确实把HTTPS解密关了就好了
之前一直是shadows，好像就是你之前的版本吧？如果没记错，记错就不好意思啦~也是没有问题的
还有在用的就是h2y的黑名单+广告了，也是没问题的

**Comment by ConnersHua** [comment]
ShadowS 也是我的，因为据我测试该问题是从 2.1.23 开始的，2.1.22 和 Pepi 上无此问题，比如将「HTTPS 解密」中的「*.googleapis.com」删除后 Google+、Hangouts 即可使用了

h2y 那边我看了下他没有用到 MitM 功能

**Comment by irenz** [comment]
好的，那我先关了https解密用着吧，感谢解答疑问，节日快乐哦

**Comment by ConnersHua** [comment]
嗯嗯，节日快乐~我稍后更新一个版本先把「*.googleapis.com」剔除掉
