### ISSUE TITLE
shadowrocket用专业配置，联通营业厅app不能登陆

### ISSUE THREAD

**Issue by jkd12138** [ConnersHua/Profiles#37]
证书安装并信任了。

**Comment by ConnersHua** [comment]
Shadowrocket 如有遇上 Youtube、知乎 等等不开的情况请确保「设置」>「关于本机」>「证书信任设置」里信任了证书，如还是有此问题可尝试重新安装信任新证书，最新 2.1.23 的「HTTPS 解密」存在问题建议关闭此功能使用，TestFlight 用户降回 2.1.22 可避免此类问题
