### ISSUE TITLE
请增加Sling/DirectNow等直播流媒体的规则，谢谢

### ISSUE THREAD

**Issue by outcastveron** [ConnersHua/Profiles#38]
RT

**Comment by ConnersHua** [comment]
这个请等几日我准备改成白名单模式规则了

**Comment by outcastveron** [comment]
> 这个请等几日我准备改成白名单模式规则了

之后是流媒体都走白名单？

**Comment by ConnersHua** [comment]
总的来讲是国外都走代理（但是我会对 Apple 等改成直连），你是希望有哪些国外服务不走代理吗

**Comment by outcastveron** [comment]
我机场流量比较足，还好。手机也没什么下载业务
还是拆开的好，有的朋友还是流量紧的

**Comment by ConnersHua** [comment]
我也一直在考虑这个问题，但是目前来说是有点难以为继了，我稍后推个含 Sling 和 DirectNow 代理的规则上去给你用着先吧

**Comment by outcastveron** [comment]
多谢，辛苦辛苦

**Comment by ConnersHua** [comment]
推上去了，因为没有账号测试我是用的 User-Agent 规则，你看看可以正常使用没
