### ISSUE TITLE
无法全局使用，direct删掉后没事但会出现其他问题

### ISSUE THREAD

**Issue by Richardzhi11** [ConnersHua/Profiles#40]

**Comment by ConnersHua** [comment]
用的什么？

**Comment by Richardzhi11** [comment]
> 用的什么？给的信息过少

surge，全局进不了谷歌，把direct的规则删掉后才能全局。我是把direct删掉后，再把fina proxy改为fina direct解决的

**Comment by ConnersHua** [comment]
Surge 全局模式不经过规则，测试过了全局下 Google 也没有问题

**Comment by Richardzhi11** [comment]
> 测试过了全局下 Google 也没有问题，规则不会影响到全局模式


> 测试过了全局下 Google 也没有问题，规则不会影响到全局模式

我还是不行，我觉得有可能和系统有关，我是ios12.1

**Comment by ConnersHua** [comment]
开「全局模式」然后开「抓取流量」看看是 Google 相关是怎么请求失败的

**Comment by Richardzhi11** [comment]
> 开「全局模式」然后开「抓取流量」看看是 Google 相关是怎么请求失败的

好

**Comment by Richardzhi11** [comment]
> > 开「全局模式」然后开「抓取流量」看看是 Google 相关是怎么请求失败的
> 
> 好在全局时使用的策略为DIRECT；Disconnect with reason: Failed to establish connection (Attempt to connect to host timed out)

**Comment by Richardzhi11** [comment]
> 全局下选的哪个节点就是走哪个节点怎么会是 DIRECT，你上截图来看下是怎么设置的

![176b9b11-db2c-4ef8-8eed-d8f3180cedbb](https://user-images.githubusercontent.com/30168380/47907748-c8e2d580-dec6-11e8-99a6-513b55f49a1f.png)
![8fd8f770-a0de-4c77-84f4-0da974b4f865](https://user-images.githubusercontent.com/30168380/47907750-c8e2d580-dec6-11e8-9577-5b0e02457b10.jpeg)
![73e5fc40-70ed-4df8-a3f7-b7e042a468ad](https://user-images.githubusercontent.com/30168380/47907751-c97b6c00-dec6-11e8-8236-8aa9508c2a48.png)
![a153e438-5b47-4ce7-a44b-4c6c71fa0d32](https://user-images.githubusercontent.com/30168380/47907752-c97b6c00-dec6-11e8-89a8-8587e127aa5e.png)

**Comment by Richardzhi11** [comment]
> ![_20181102181645](https://user-images.githubusercontent.com/11730838/47909900-2e859080-decc-11e8-9da4-0d221b3a1473.jpg)
> 
> 注意一下「Global Proxy」下的是不是选到「DIRCERT」策略了

没找到Global Proxy😅

**Comment by ConnersHua** [comment]
在更新一次试试吧，我把那个选项给弄掉了
