### ISSUE TITLE
刺激战场，bilibili，知乎，也是被代理了

### ISSUE THREAD

**Issue by jkd12138** [ConnersHua/Profiles#41]
用的shadowrocket，pro规则，用workflow添加的，证书生成并信任了。
这些都是国内的软件，根本不需要被代理啊！代理了反而会有问题（刺激战场会登不上，另外两个软件加载会很慢很慢）。

**Comment by ConnersHua** [comment]
先把 DNS 中的 1.0.0.1 删掉可能解析到海外 CDN 上了，另外如果是使用最新版 Shadowrocket 不要开解密，有 Bug

**Comment by ConnersHua** [comment]
「HTTPS 解密」和代理没有关系

你是哪里的什么运营商网络，我反查下

**Comment by jkd12138** [comment]
> 「HTTPS 解密」和代理没有关系
> 
> 你是哪里的什么运营商网络，我反查下

河南新乡联通，米粉卡。

**Comment by ConnersHua** [comment]
我大概知道为什么了，现在的 DNS 设置是不是 119.28.28.28 和 223.6.6.6 ？

**Comment by ConnersHua** [comment]
没管 DNS？规则中的 DNS 会覆写系统自动获取

**Comment by jkd12138** [comment]
> 没管 DNS？规则中的 DNS 会覆写系统自动获取

我看到的dns就是我上面写的那三个

**Comment by ConnersHua** [comment]
![wechatimg57](https://user-images.githubusercontent.com/11730838/47801733-c159ea00-dd69-11e8-8a74-c14938490096.jpeg)

确认下，是在这个页面看到的是吧

**Comment by ConnersHua** [comment]
如果是想使用系统自动获取的请在此改成「system」即可

然后是关于走代理的问题，如果是我写的「119.28.28.28」那个的话那个问题的原因如下：「119.28.28.28」早前路由是香港后来转为深圳，但是国内运营商没有更新路由设置所以应该是如此导致解析到海外 CDN 上了

你先尝试改成「system」使用系统自带或是其他国内 DNS 看看能否解决吧

**Comment by jkd12138** [comment]
> 如果是想使用系统自动获取的请在此改成「system」即可
> 
> 然后是关于走代理的问题，如果是我写的「119.28.28.28」那个的话那个问题的原因如下：「119.28.28.28」早前路由是香港后来转为深圳，但是国内运营商没有更新路由设置所以应该是如此导致解析到海外 CDN 上了
> 
> 你先尝试改成「system」使用系统自带或是其他国内 DNS 看看能否解决吧

改成系统自带的正常了

**Comment by ConnersHua** [comment]
好的，感谢反馈，后续我会改下捷径

**Comment by jkd12138** [comment]
> 好的，感谢反馈，后续我会改下捷径

配置里搜索apple，有几个是direct，应该有需要改成proxy，不然不代理美区AppStore。

**Comment by ConnersHua** [comment]
App Store 走国内 CDN 的

**Comment by DNrover** [comment]
使用的是全局模式，不是按规则代理模式
