### ISSUE TITLE
[feature request]回国规则+去广告

### ISSUE THREAD

**Issue by lonelykid** [ConnersHua/Profiles#43]
希望加上这个组合

**Comment by Richardzhi11** [comment]
可以自己把去广告的规则复制进去

**Comment by ConnersHua** [comment]
Surge 和 Quantumult 已经加上了，可选策略，Shadowrocket 还没想好以什么样的形式搞

**Comment by lonelykid** [comment]
谢谢！Shadowrocket不好弄，是不支持在规则中添加select吗？

@Richardzhi11 我是基于国内的规则，删掉多余的规则，再GEOIP,CN,PROXY

**Comment by ConnersHua** [comment]
已加到现有回国规则内
