### ISSUE TITLE
google play部分应用无法下载

### ISSUE THREAD

**Issue by yubo780429** [ConnersHua/Profiles#47]
例如：[https://play.google.com/store/apps/details?id=com.leagueofgeeks.armello&hl=zh](url)或
[https://play.google.com/store/apps/details?id=com.cle.dy.soulseeker6](url)

显示状态为：正在下载，实际没有产生任何流量无法下载。
并不是所有的APP都会出现上述情况，是否部分域名被错误的阻挡所导致？

**Comment by ConnersHua** [comment]
Google 家的只有广告域名被拦，不会影响到这个，安卓各机型对于 Play 商店下载表现也不一样，目前见过的几种：
1.走 gvt1.com 的（我的）
2.走 IP 的（国行机型居多）
3.走 xn--ngstr-lra8j.com 的（三星机型居多）

如果是在用 Surfboard，可以把除了 Play 商店和 Surfboard 外的 App 都关掉，在 Surfboard 的「Setting > Recent Requests」打开，然后再点击下载，看看具体请求了什么

**Comment by yubo780429** [comment]
> Google 家的只有广告域名被拦，不会影响到这个，安卓各机型对于 Play 商店下载表现也不一样，目前见过的几种：
> 1.走 gvt1.com 的（我的）
> 2.走 IP 的（国行机型居多）
> 3.走 xn--ngstr-lra8j.com 的（三星机型居多）
> 
> 如果是在用 Surfboard，可以把除了 Play 商店和 Surfboard 外的 App 都关掉，在 Surfboard 的「Setting > Recent Requests」打开，然后再点击下载，看看具体请求了什么

DNS污染，解析xn--ngstr-lra8j.com错误，已解决。

**Comment by ConnersHua** [comment]
噗，上次看还没污染，感谢反馈
