### ISSUE TITLE
在登录校园网时要关闭surge才能登录上

### ISSUE THREAD

**Issue by Richardzhi11** [ConnersHua/Profiles#48]
有什么办法解决不？我试着把dns改成学校运营商的也没有用😂是不是这个软件或者这类软件都不能这样🧐🤔

**Comment by ConnersHua** [comment]
仅使用系统 DNS 看看能不能解决，Surge、Shadowrocket 设为 system

**Comment by ConnersHua** [comment]
尝试把登录验证页面的 IP 或者网址加到 skip-proxy 里面看看

**Comment by Richardzhi11** [comment]
> 尝试把登录验证页面的 IP 或者网址加到 skip-proxy 里面看看

那是个客户端，抓包抓不出

**Comment by ConnersHua** [comment]
囧

**Comment by Richardzhi11** [comment]
> 囧
拿电脑抓试试

**Comment by Richardzhi11** [comment]
解决了，谢谢🙏
