### ISSUE TITLE
Surge Pro 无法打开 Apple News 了

### ISSUE THREAD

**Issue by whereiswhere** [ConnersHua/Profiles#50]
APPLE 配置是选的 PROXY， 而且系统里区域设置是美国，但是打开 Apple News 显示所在区域不支持。另外在 Apple Books Store 里 Get Sample 也说所在区域不可用之类的。

之前的一个 Surge Profile 好像是正常的，但是更定到最新的之后出现这个问题了。

**Comment by ConnersHua** [comment]
我的锅，已经修复了，再更新一次吧
