### ISSUE TITLE
提交关于Brawl Stars(荒野乱斗)的规则

### ISSUE THREAD

**Issue by ceadmond** [ConnersHua/Profiles#51]
# > Brawl Stars
DOMAIN,inbox.brawlstars.com,PROXY
DOMAIN,game.brawlstarsgame.com,PROXY
DOMAIN,1681.engine.mobileapptracking.com,PROXY
DOMAIN,ingame.id.supercell.com,PROXY
DOMAIN,cdn.supercell.com,PROXY
DOMAIN,s.ytimg.com,PROXY

**Comment by ConnersHua** [comment]
已加

**Comment by ceadmond** [comment]
但是surfboard并不支持user-agent类型的规则

2019年1月15日 上午11:48，"Conners Hua" <notifications@github.com>写道：

已加

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ConnersHua/Profiles/issues/51#issuecomment-454257933>,
or mute the thread

**Comment by ceadmond** [comment]
还有我不知道皇室战争的规则是不是针对谷歌版的，因为皇室战争在国内有很多代理版本，会不会影响国内版本

Conners Hua <notifications@github.com> 于 2019年1月15日周二 下午12:30写道：

**Comment by ConnersHua** [comment]
这种情况用使用 PROCESS-NAME 规则
