### ISSUE TITLE
kitsunebi黑名单模式无法正常访问外网

### ISSUE THREAD

**Issue by sizhex** [ConnersHua/Profiles#56]
如题。

**Comment by ConnersHua** [comment]
哪个外网？

**Comment by sizhex** [comment]
规则采用kitsunebi Pro ,IOS 12,路由模式采用BLACKLIST，谷歌，Facebook等墙外网站均无法访问，运营商江苏联通，DNS填了2个119.29.29.29和23.5.5.5

**Comment by ConnersHua** [comment]
黑名单不可用是我改白名单的原因，等我几分钟把常见污染传上去

**Comment by sizhex** [comment]
> 黑名单不可用是我改白名单的原因，等我几分钟把常见污染传上去

感谢！

**Comment by ConnersHua** [comment]
好了，另外新版 Kits 中我对于 DNS 有一些处理是规则控制的，不要删除默认规则同步下来的 223.5.5.5 和 8.8.8.8，特别是后者删除了会导致污染问题处理不了

**Comment by sizhex** [comment]
> 好了，另外新版 Kits 中我对于 DNS 有一些处理是规则控制的，不要删除默认规则同步下来的 223.5.5.5 和 8.8.8.8，特别是后者删除了会导致污染问题处理不了

好的，试了下OK了
