### ISSUE TITLE
surge3版没有去新浪微博开屏广告的规则,而Quantumult和Shadowrocket中的规则有,望修复这个问题.

### ISSUE THREAD

**Issue by renjie45** [ConnersHua/Profiles#60]
# > Sina Weibo
^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkad\.php - reject
^https?:\/\/wbapp\.uve\.weibo\.com\/wbapplua\/wbpullad\.lua - reject
^https?:\/\/sdkapp\.uve\.weibo\.com/\interface\/sdk\/actionad\.php - reject
surge3去广告规则中没有找到这几三条.

**Comment by ConnersHua** [comment]
![image](https://wx2.sinaimg.cn/large/0071qmuFgy1fzonu6y71vj316y0bc77j.jpg)

???

**Comment by renjie45** [comment]
我知道原因了,我用捷径导入的和直接用URL导入的会不一样.捷径导入的不能去掉微博国标版的开屏广告,我用URL导入的可以去掉开屏广告.捷径导入的显示17条规则,URL导入的显示18条规则.

这是捷径导入生成的配置文件:
[General]
loglevel = warning
skip-proxy = 192.168.0.0/16, 193.168.0.0/24, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 17.0.0.0/8, 127.0.0.1, localhost, *.local
ipv6 = false
show-error-page-for-reject = true
dns-server = system,119.29.29.29,223.5.5.5
allow-wifi-access = false


[Rule]
# Advertising Block 去广告以及隐私追踪保护
RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Advertising.list,ADVERTISING
# Hijacking Protection 反运营商及臭名昭著的应用劫持保护
RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Hijacking.list,HIJACKING,notification-text="⚠️ 遭受劫持，如页面异常请刷新"
# Media 媒体应用（Youtube、Netflix、HBO、Hulu、BBC iPlayer、Bahamut、myTV SUPER、AbemaTV 和 JOOX）
RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Media.list,MEDIA
# Global 全球加速规则
RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Global.list,PROXY
# Apple 部分服务加速（App Store、Movies、Music、News 及海外版 Maps）
RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Apple.list,APPLE
# China 中国直连规则
RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/China.list,DIRECT
# Local Area Network
RULE-SET,LAN,DIRECT
# GeoIP China
GEOIP,CN,DIRECT
FINAL,PROXY,dns-failed

[Host]
*.taobao.com = server:223.5.5.5
*.tmall.com = server:223.5.5.5

[URL Rewrite]
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
^https?:\/\/(www.)?taobao\.com\/ https://taobao.com/ 302
^https?:\/\/(www.)?jd\.com\/ https://www.jd.com/ 302
^https?:\/\/(www.)?mi\.com\/ https://www.mi.com/ 302
^https?:\/\/you\.163\.com\/ https://you.163.com/ 302
^https?:\/\/(www.)?suning\.com/ https://suning.com/ 302
^https?:\/\/(www.)?yhd\.com https://yhd.com/ 302
^https?:\/\/(www.)?ign\.xn--fiqs8s\/ http://cn.ign.com/ccpref/us 302
^https?:\/\/(www.)?abbyychina\.com\/ http://www.abbyy.cn/ 302
^https?:\/\/(www.)?bartender\.cc\/ https://cn.seagullscientific.com 302
^https?:\/\/(www.)?betterzip\.net\/ https://macitbetter.com/ 302
^https?:\/\/(www.)?beyondcompare\.cc\/ https://www.scootersoftware.com/ 302
^https?:\/\/(www.)?bingdianhuanyuan\.cn\/ http://www.faronics.com/zh-hans/ 302
^https?:\/\/(www.)?chemdraw\.com\.cn\/ http://www.cambridgesoft.com/ 302
^https?:\/\/(www.)?codesoftchina\.com\/ https://www.teklynx.com/ 302
^https?:\/\/(www.)?coreldrawchina\.com\/ https://www.coreldraw.com/cn/ 302
^https?:\/\/(www.)?crossoverchina\.com\/ https://www.codeweavers.com/ 302
^https?:\/\/(www.)?easyrecoverychina\.com\/ https://www.ontrack.com/ 302
^https?:\/\/(www.)?ediuschina\.com\/ https://www.grassvalley.com/ 302
^https?:\/\/(www.)?flstudiochina\.com\/ https://www.image-line.com/flstudio/ 302
^https?:\/\/(www.)?formysql\.com\/ https://www.navicat.com.cn 302
^https?:\/\/(www.)?guitarpro\.cc\/ https://www.guitar-pro.com/ 302
^https?:\/\/(www.)?huishenghuiying\.com\.cn\/ https://www.corel.com/cn/ 302
^https?:\/\/(www.)?iconworkshop\.cn\/ https://www.axialis.com/iconworkshop/ 302
^https?:\/\/(www.)?imindmap\.cc\/ https://imindmap.com/zh-cn/ 302
^https?:\/\/(www.)?jihehuaban\.com\.cn\/ https://sketch.io/ 302
^https?:\/\/(www.)?keyshot\.cc\/ https://www.keyshot.com/ 302
^https?:\/\/(www.)?mathtype\.cn\/ http://www.dessci.com/en/products/mathtype/ 302
^https?:\/\/(www.)?mindmanager\.cc\/ https://www.mindjet.com/ 302
^https?:\/\/(www.)?mindmapper\.cc\/ https://mindmapper.com 302
^https?:\/\/(www.)?mycleanmymac\.com\/ https://macpaw.com/cleanmymac 302
^https?:\/\/(www.)?nicelabel\.cc\/ https://www.nicelabel.com/ 302
^https?:\/\/(www.)?ntfsformac\.cc\/ https://www.tuxera.com/products/tuxera-ntfs-for-mac-cn/ 302
^https?:\/\/(www.)?ntfsformac\.cn\/ https://www.paragon-software.com/ufsdhome/zh/ntfs-mac/ 302
^https?:\/\/(www.)?overturechina\.com\/ https://sonicscores.com/overture/ 302
^https?:\/\/(www.)?passwordrecovery\.cn\/ https://cn.elcomsoft.com/aopr.html 302
^https?:\/\/(www.)?pdfexpert\.cc\/ https://pdfexpert.com/zh 302
^https?:\/\/(www.)?ultraiso\.net\/ https://cn.ezbsystems.com/ultraiso/ 302
^https?:\/\/(www.)?vegaschina\.cn\/ https://www.vegas.com/ 302
^https?:\/\/(www.)?xmindchina\.net\/ https://www.xmind.cn/ 302
^https?:\/\/(www.)?xshellcn\.com\/ https://www.netsarang.com/products/xsh_overview.html 302
^https?:\/\/(www.)?yuanchengxiezuo\.com\/ https://www.teamviewer.com/zhcn/ 302
^https?:\/\/(www.)?zbrushcn\.com\/ http://pixologic.com/ 302
(?<=&carrier_region=)CN(?=&is_my_cn=1) JP 307
^https?:\/\/app\.58\.com\/api\/home\/advertising\/ - reject
^https?:\/\/app\.58\.com\/api\/home\/appadv\/ - reject
^https?:\/\/app\.58\.com\/api\/home\/invite\/popupAdv - reject
^https?:\/\/app\.58\.com\/api\/log\/ - reject
^https?:\/\/.+\.58cdn\.com\.cn\/brandads\/ - reject
^https?:\/\/aes\.acfun\.cn\/s\?adzones - reject
^https?:\/\/gw\.aihuishou\.com\/app-portal\/home\/getadvertisement - reject
^https?:\/\/update\.pan\.baidu\.com\/statistics - reject
^https?:\/\/issuecdn\.baidupcs\.com\/issue\/netdisk\/guanggao\/ - reject
^https?:\/\/.+\.pstatp\.com\/img\/ad - reject
^https?:\/\/.+\.(musical|snssdk)\.(com|ly)\/(api|motor)\/ad\/ - reject
^https?:\/\/dsp\.toutiao\.com\/api\/xunfei\/ads\/ - reject
^https?:\/\/.+\.snssdk\.com\/motor\/operation\/activity\/display\/config\/V2\/ - reject
^https?:\/\/www\.myhug\.cn\/ad\/ - reject
^http:\/\/7n\.bczcdn\.com\/launchad\/ - reject
^https?:\/\/creditcard\.ecitic\.com\/citiccard\/wtk\/piwik\/piwik\.php - reject
^https?:\/\/m\.creditcard\.ecitic\.com\/citiccard\/mbk\/appspace-getway\/getWay\/appspace-system-web\/cr\/v5\/appStartAdv - reject
^https?:\/\/mlife\.cmbchina\.com/ClientFaceService\/preCacheAdvertise\.json - reject
^https?:\/\/mlife\.cmbchina\.com\/ClientFaceService\/getAdvertisement\.json - reject
^https?:\/\/www\.cmbc\.com\.cn\/m\/image\/loadingpage\/ - reject
^https?:\/\/app\.10086\.cn\/biz-orange\/DN\/(findSale|homeSale)\/getsaleAdver - reject
^https?:\/\/m\.client\.10010\.com\/mobileService\/customer\/accountListData\.htm - reject
^https?:\/\/m\.client\.10010\.com\/uniAdmsInterface\/(getWelcomeAd|getHomePageAd) - reject
^https?:\/\/cntv\.hls\.cdn\.myqcloud\.com\/.+\?maxbr=850 - reject
^https?:\/\/asp\.cntv\.myalicdn\.com\/.+\?maxbr=850 - reject
^https?:\/\/www\.cntv\.cn\/nettv\/adp\/ - reject
^https?:\/\/v\.cctv\.com\/.+850 - reject
^https?:\/\/(api|atrace)\.chelaile\.net\.cn\/adpub\/ - reject
^https?:\/\/api\.chelaile\.net\.cn\/goocity\/advert\/ - reject
^https?:\/\/atrace\.chelaile\.net\.cn\/exhibit\?&adv_image - reject
^https?:\/\/pic1\.chelaile\.net\.cn\/adv\/ - reject
^https?:\/\/api\.douban\.com\/v2\/app_ads\/ - reject
^https?:\/\/erebor\.douban\.com\/count\/\?ad= - reject
^https?:\/\/.+\.doubanio\.com\/view\/dale-online\/dale_ad/ - reject
^https?:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo - reject
^https?:\/\/mapi\.dangdang\.com\/index\.php\?action=init - reject
^https?:\/\/api\.daydaycook\.com\.cn\/daydaycook\/server\/ad\/ - reject
^https?:\/\/cms\.daydaycook\.com\.cn\/api\/cms\/advertisement\/ - reject
^https?:\/\/.+/(adgateway|adv)/ - reject
^https?:\/\/foodie-api\.yiruikecorp\.com\/v1\/(banner|notice)\/overview - reject
^https?:\/\/cdn\.api\.fotoable\.com\/Advertise\/ - reject
^https?:\/\/.+\.youtube\.com\/get_midroll - reject
^https?:\/\/premiumyva\.appspot\.com\/vmclickstoadvertisersite - reject
^https?:\/\/.+\.youtube\.com\/api\/stats\/ads - reject
^https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat - reject
^https?:\/\/.+\.youtube\.com\/pagead\/ - reject
^https?:\/\/.+\.youtube\.com\/ptracking\? - reject
^https?:\/\/m\.ibuscloud.com\/v2\/app\/getStartPage - reject
^https?:\/\/smkmp\.96225.com\/smkcenter\/ad/ - reject
^https?:\/\/games\.mobileapi\.hupu\.com\/.+\/status\/init - reject
^https?:\/\/games\.mobileapi\.hupu\.com\/.+\/interfaceAdMonitor\/ - reject
^https?:\/\/imeclient\.openspeech\.cn\/adservice\/ - reject
^https?:\/\/iface\.iqiyi\.com\/api\/getNewAdInfo - reject
^https?:\/\/.+\/(mixer|track2)\? - reject
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start - reject
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ - reject
^https?:\/\/ms\.jr\.jd\.com\/gw\/generic\/base\/na\/m\/adInfo - reject
^https?:\/\/img\.jiemian\.com\/ads\/ - reject
^https?:\/\/api\.jxedt\.com\/ad\/ - reject
^https?:\/\/richmanapi\.jxedt\.com\/api\/ad\/ - reject
^https?:\/\/static1\.keepcdn\.com\/.+\d{3}x\d{4} - reject
^https?:/\/\counter\.ksosoft.com\/ad\.php - reject
^https?:\/\/ios\.wps\.cn\/ad-statistics-service - reject
^https?:\/\/mobile-pic\.cache\.iciba\.com\/feeds_ad\/ - reject
^https?:\/\/.+\.kingsoft-office-service\.com\/ad - reject
^https?:\/\/counter\.ksosoft\.com\/ad\.php - reject
^https?:\/\/dict-mobile\.iciba\.com\/interface\/index\.php\?.+(c=ad|collectFeedsAdShowCount|KSFeedsAdCardViewController) - reject
^https?:\/\/service\.iciba\.com\/popo\/open\/screens\/v3\?adjson - reject
^https?:\/\/api\.kkmh\.com\/.+(ad|advertisement)\/ - reject
^https?:\/\/.+\/letv-gug\/ - reject
^https?:\/\/api\.m\.mi\.com\/v1\/app\/start - reject
^https?:\/\/api\.jr\.mi\.com\/v1\/adv\/ - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/homepage_ad\? - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/sleep_ad\? - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/sport_ad\? - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/sport_summary_ad\? - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/sport_training_ad\? - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/step_detail_ad\? - reject
^https?:\/\/api-mifit\.huami\.com\/discovery\/mi\/discovery\/training_video_ad\? - reject
^https?:\/\/api\.mgzf\.com\/renter-operation\/home\/startHomePage - reject
^https?:\/\/cdn\.moji\.com\/(adoss|adlink)\/ - reject
^https?:\/\/.+\/api\/app\/member\/ver2\/user\/login\/ - reject
^https?:\/\/mob\.mddcloud\.com\.cn\/api\/(ad|advert)\/ - reject
^https?:\/\/mangaapi\.manhuaren\.com\/v1\/public\/getStartPageAds - reject
^https?:\/\/img\.meituan\.net\/midas\/ - reject
^https?:\/\/p\d{1}\.meituan\.net\/(display|mmc|wmbanner)\/ - reject
^https?:\/\/capi.mwee.cn/app-api/V12/app/getstartad - reject
^https?:\/\/.+\/v1\/iflyad\/ - reject
^https?:\/\/.+\/cdn-adn\/ - reject
^https?:\/\/ggic\.cmvideo\.cn\/ad\/ - reject
^https?:\/\/ggic2\.cmvideo\.cn\/ad\/ - reject
^https?:\/\/.+/img\/ad\.union\.api\/ - reject
^https?:\/\/b-api\.ins\.miaopai\.com\/1\/ad/ - reject
^https?:\/\/oimage([a-z])([0-9])\.ydstatic\.com\/.+adpublish - reject
^https?:\/\/dsp-impr2\.youdao\.com\/adload.s\? - reject
^https?:\/\/c\.m\.163\.com\/nc\/gl\/ - reject
^https?:\/\/client\.mail\.163\.com\/apptrack\/confinfo\/searchMultiAds - reject
^https?:\/\/.+\/eapi\/(ad|log)\/ - reject
^https?:\/\/sp\.kaola\.com\/api\/openad - reject
^https?:\/\/support\.you\.163\.com\/xhr\/boot\/getBootMedia\.json - reject
^https?:\/\/supportda\.ofo\.com\/adaction\? - reject
^https?:\/\/ma\.ofo\.com\/ads\/ - reject
^https?:\/\/activity2\.api\.ofo\.com\/ofo\/Api\/v2\/ads - reject
^https?:\/\/ma\.ofo\.com\/adImage\/ - reject
^https?:\/\/cmsapi\.wifi8\.com\/v\d{1}\/(emptyAd|adNew)\/ - reject
^https?:\/\/app3\.qdaily\.com\/app3\/boot_advertisements\.json - reject
^https?:\/\/notch\.qdaily\.com\/api\/v2\/boot_ad - reject
^https?:\/\/open\.qyer\.com\/qyer\/startpage\/ - reject
^https?:\/\/open\.qyer.com\/qyer\/config\/get - reject
^https?:\/\/media\.qyer\.com\/ad\/ - reject
^https?:\/\/edit\.sinaapp\.com\/ua\?t=adv - reject
^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkad\.php - reject
^https?:\/\/wbapp\.uve\.weibo\.com\/wbapplua\/wbpullad\.lua - reject
^https?:\/\/sdkapp\.uve\.weibo\.com/\interface\/sdk\/actionad\.php - reject
^https?:\/\/tqt\.weibo\.cn\/overall\/redirect\.php\?r=tqt_sdkad - reject
^https?:\/\/tqt\.weibo\.cn\/overall\/redirect\.php\?r=tqtad - reject
^https?:\/\/tqt\.weibo\.cn\/.+advert\.index - reject
^https?:\/\/api\.k\.sohu\.com\/api\/news\/adsense - reject
^https?:\/\/pic\.k\.sohu\.com\/img8\/wb\/tj\/ - reject
^https?:\/\/s1\.api\.tv\.itc\.cn\/v4\/mobile\/control\/switch\.json - reject
^https?:\/\/api\.smzdm\.com\/v1\/util\/loading - reject
^https?:\/\/service\.4gtv\.tv\/4gtv\/Data\/GetAD - reject
^https?:\/\/service\.4gtv\.tv\/4gtv\/Data\/ADLog - reject
^https?:\/\/api\.qiuduoduo\.cn\/guideimage - reject
^https?:\/\/api5\.futunn\.com\/ad\/ - reject
^https?:\/\/newsso\.map\.qq\.com\/\?&attime= - reject
^https?:\/\/btrace.qq.com - reject
^https?:\/\/vv\.video\.qq\.com\/getvmind\? - reject
^https?:\/\/.+\.mp4\?cdncode=.+&guid= - reject
^https?:\/\/r\.inews\.qq\.com\/getFullScreenPic - reject
^https?:\/\/r\.inews\.qq\.com\/adsBlacklist - reject
^https?:\/\/r\.inews\.qq\.com\/getQQNewsRemoteConfig - reject
^https?:\/\/ssl\.kohsocialapp\.qq\.com:10001\/game\/buttons - reject
^https?:\/\/mp\.weixin\.qq.com\/mp\/ad_complaint - reject
^https?:\/\/mp\.weixin\.qq.com\/mp\/advertisement_report - reject
^https?:\/\/mp\.weixin\.qq.com\/mp\/ad_video - reject
^https?:\/\/images\.client\.vip\.xunlei\.com\/.+\/advert\/ - reject
^https?:\/\/api\.gaoqingdianshi\.com\/api\/v2\/ad\/ - reject
^https?:\/\/adpai\.thepaper\.cn\/.+&ad= - reject
^https?:\/\/agent-count\.pconline\.com\.cn\/counter\/adAnalyse\/ - reject
^https?:\/\/mrobot\.pconline\.com\.cn\/v3\/ad2p - reject
^https?:\/\/mrobot\.pconline\.com\.cn\/s\/onlineinfo\/ad\/ - reject
^https?:\/\/mrobot\.pcauto\.com\.cn\/v3\/ad2p - reject
^https?:\/\/mrobot\.pcauto\.com\.cn\/xsp\/s\/auto\/info\/preload\.xsp - reject
^https?:\/\/huichuan\.sm\.cn\/jsad - reject
^https?:\/\/iflow\.uczzd\.cn\/log\/ - reject
^https?:\/\/app\.wy\.guahao\.com\/json\/white\/dayquestion\/getpopad - reject
^https?:\/\/overseas\.weico\.cc/portal\.php\?a=get_coopen_ads - reject
^https?:\/\/api-release\.wuta-cam\.com\/ad_tree - reject
^https?:\/\/res-release\.wuta-cam\.com\/json\/ads_component_cache\.json - reject
^https?:\/\/snailsleep\.net\/snail\/v1\/screen\/qn\/get\? - reject
^https?:\/\/snailsleep\.net\/snail\/v1\/adTask\/ - reject
^https?:\/\/api\.xiachufang\.com\/v2\/ad/ - reject
^https?:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alimusic\.common\.mobileservice\.startinit\/ - reject
^https?:\/\/m\.yap\.yahoo\.com\/v18\/getAds\.do - reject
^http:\/\/api\.catch\.gift\/api\/v3\/pagead\/ - reject
^https?:\/\/.+\.mp4\?ccode=0902 - reject
^https?:\/\/.+\.mp4\?sid= - reject
^https?:\/\/ctrl\.(playcvn|zmzapi)\.(com|net)\/app\/(ads|init) - reject
^https?:\/\/i\.ys7\.com\/api\/ads - reject
^https?:\/\/.+\.iydsj\.com\/api\/.+\/ad - reject
^https?:\/\/app\.mixcapp\.com\/mixc\/api\/v2\/ad - reject
^https?:\/\/a\.qiumibao\.com\/activities\/config\.php - reject
^https?:\/\/.+\/allOne\.php\?ad_name - reject
^https?:\/\/www\.zhihu\.com\/api\/v4\/community-ad\/ - reject
^https?:\/\/api\.zhihu\.com\/real_time_launch - reject
^https?:\/\/api\.zhihu\.com\/launch - reject

[Header Rewrite]
^https?://www\.zhihu\.com header-replace User-Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
^https?://zhidao\.baidu\.com header-replace User-Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

[SSID Setting]
"Apple Store" suspend=true

[MITM]
skip-server-cert-verify = true
hostname = *.chelaile.net.cn, *.douban.com, *.doubanio.com, *.iydsj.com, *.k.sohu.com, *.kingsoft-office-service.com, *.meituan.net, *.ofo.com, *.pstatp.com, *.snssdk.com, *.uve.weibo.com, *.ydstatic.com, *.youdao.com, *.youtube.com, a.qiumibao.com, acs.m.taobao.com, api.daydaycook.com.cn, api.jr.mi.com, api.jxedt.com, api.kkmh.com, api.m.jd.com, api.mgzf.com, api.smzdm.com, api-release.wuta-cam.com, api*.tiktokv.com, api*.musical.ly, api.weibo.cn, api.xiachufang.com, api.zhihu.com, api5.futunn.com, app.10086.cn, app.58.com, app.wy.guahao.com, app.mixcapp.com, c.m.163.com, capi.mwee.cn, cdn.moji.com, client.mail.163.com, cms.daydaycook.com.cn, creditcard.ecitic.com, huichuan.sm.cn, i.ys7.com, iface.iqiyi.com, img.jiemian.com, ios.wps.cn, m.client.10010.com, m.creditcard.ecitic.com, m.ibuscloud.com, m.yap.yahoo.com, media.qyer.com, mlife.cmbchina.com, mob.mddcloud.com.cn, mp.weixin.qq.com, mrobot.pcauto.com.cn, mrobot.pconline.com.cn, ms.jr.jd.com, newsso.map.qq.com, open.qyer.com, richmanapi.jxedt.com, r.inews.qq.com, res-release.wuta-cam.com, rtbapi.douyucdn.cn, service.4gtv.tv, smkmp.96225.com, snailsleep.net, sp.kaola.com, ssl.kohsocialapp.qq.com, static1.keepcdn.com, support.you.163.com, www.zhihu.com, zhidao.baidu.com
ca-passphrase = 15F5092B
ca-p12 = MIIJtAIBAzCCCX4GCSqGSIb3DQEHAaCCCW8EgglrMIIJZzCCA9cGCSqGSIb3DQEHBqCCA8gwggPEAgEAMIIDvQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIb9u68FCUtaICAggAgIIDkJmdLPCzX5lJ1TPDjgq5/LgB2VL/vPL9YHy3MRnhXg1+ib18H73x1vNM330PD08ll+5tsp07CgFCw5fch8EfpJAbxvMrQN/qnns9KUWZk8H64sav2ToUIykSWQR3f9R562cf12/t2oid+RvOh+JkS6l2c58NE9X+wQq8vGv80G0Ep0M7E0mTlsOE29xeTj1XtDE9N2jge67E9SRI83E0CmGlo0fvTkOoxmkqrAdha91g5k8B52Zqu07ju7gyHFeEjVS4VxWk6812d+3ojypbGWlGd+oSnaQMdVZS9VOul57xMfsf+3InMHpExqeujBGySaNCvonoArNIAONreq9Impqivk2FuXGHNj+yBEiZeYtneZuc6FdoTvH6oH3eAj5QzpQbvapp/d15zSPQ3rKTHQ2o71sC3pt7xaTiUFgQHNVPBUR6gtctXQj4C9kqE9aKHXp236DKRNK3wdrDMamxoJQpkYXAnxpc+K6Jte0Zk7l9tm0nIaqOSe0zUs08ZKJFWoyZXD4dkO5xdIdVGEV+hvn5DeAly1H+gsgHR4cLAW0eIWLjGgwT4CuoINUGU86d2y8dpkblB0FtEQeIxlUqH4/Ha184YUkq10gyv3NXo9A5vwIa0twRfLVIJD4ZBmPx9WL1XGd+wks7HVy8UZbi1+tOL/2G1T/Ua6QVE4DfACtMLAf1FfGWwz0WntPNSRuLeY6m3ug9DkbQCoguDP5y6HK2af3JJDHJ/nFAwOisZKIFSvVsbH3lunl42BzZ6J2d5I+PyytpDzTcPqkbkL/Cov4MI6V3AhhHAubhQgB26h2IXMK96mamj3GSwYV9TOCrwC4XBt8UE3n/mKKG9aCnAm5LsbkjO9CAJ6ueBdCoXgdFTSjCWdEBzkera2rCyijkJ1rS7LXCd+81zrApmClqlErRNSVLznHVrLCQp8W+XqxvzeTXNZEGzwc4wywb85FW/G8IKIMm6rLjvENr1wbKXkwcyhyLvQWQW6wgQf9S9LXgO4di1E4OiqEQqusalVVZ2tIWWsB9SAjFkZw5n3LZ4WDN95zWcOmoBtcM3qETzU9ZbUavAUgnyfKT3nyACr64kg0CCOrUAPLVu3d6xt/0SjrWPM3dlUGJmGbth57L+if7NQwjmkcNmKVoOkZ/ps8fQislJiVb4qWBofhF8JeFCnKily3CQJ2c+5JG6TZ7xpJeOfwnDSFReV2sNoqLqjKsETCCBYgGCSqGSIb3DQEHAaCCBXkEggV1MIIFcTCCBW0GCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAhyqaZ63YAPrwICCAAEggTIjf2zL0ibegsa6nZSH+jC55iI+Ai1mDtS/prYW9koUUutkavWQJePj5i2yQiQ+qnZ7cd834ODUYreCAnW3Aal78j6GeJrIzi8uYSmTjz7sYiw1bBgYuqYSTW2D4/1hjgWgyxLS10b5mZseihEK/U4v02onKkWTXCxocjiKosfFTu1rlZto9bWFUm/IeTsEkKoYuGy2nO1o7yyY/pbLO4+sdIy/8919RqzNmnP4sHhjuAyNrWZ8wJbDU7BLogAYDYDsDOiE/hcSm2F8wrDkm0FQOVUXm8RoxSn464wUNLe1ZQ4iM5RB06SGfUhx98iQZmSes+O3lHYRbDOohWKCoC7QW15dhWqSQRgCVDtvUj8OJnBxB4rO7faoUMg6dqSKcx9JBROog1xar6aMp3T7x9H2WmjkmaCPabgCma/McTQyDYWW33JA7QR8Xco/7Pf8x1zFMD5cpIWdeVGJ1haBq07ulPMK5RcsOLv2/kVInAH1kzpQj/eyMvr52QstL2pF87I71Uh6J+tAe4uH7gFn8yGZhTbRBQ/OZnPZJfhEKU5S4HFyH/Tx4xovcne/wpe1o8WKVyUUgyCoxkEcushxiR4LJsgcvTRFmRgk3t+XF8FXMD8a1bOp9RkAzuVrZo/D9gsDRCedkmT/NZofAN1nA7EveP05rGQOLSTdOZWRUcYgzlKEQbnAcxDJ95C4ZvtxyqHUtqjI3pcBWTRqOi/UI6uiwfrFE5nOr629uH0v8lrM3AKzyKRvTpz3AtpKAaMjCKcstE4CM+zLX+mVJuVY6atK59n0MTce8OITKikVaRECZg1jv+IX4OLrmmQcwfioc0xEKVxZs90oJRJHM9k8LdtS6YcyJw8xOsvqN2uNREvg/OrHJ8we5+zEEHI1jm75mFBV+hyZAGQeshjroUAaniwJx5I1uIp23ZNbG1T5vIjtuONmwXLhJGSH98L6XF4e9hmGvMHIDPzWpG0U7unNZwQpn9BmdCs19rF0Jto9OmKnW5cnFvvz2y7cUW0zAzVRGsjieHff/Wz4HVg2te/fjKOMMxl0ncH6ShsBCKd3KtBF1amNjcITzbN7cUiSGY+l6ZjV+XLA+BAFxaOp7uPFqURc9YLgPHC31vcpucj7BzVWnmupL5RJC4nSkk4wArZABvHxYQfxI7H3XMPRzRDBK1i4t0iwysvbIvuOwxBP5WYEEy5o4/xFjmAeZBe8AuPcPqg/Z1JR7OhthqCP7NX6az9ZfSDNha/fq+bCQnbMV/INFULGG4NmBVGwJ1I8UyY9pPijMF67PBUFzsxpfVoZHffps6qJOJFJZLsEPlbij15CFCXtktBx3VvWPghDKDDu2D8JeFiatHShGLw5SIBjayb8z4Bf6EaXe6ZAwWkJccbYhYR/C6qb2IUfVB7TVBojB1kMLF9GAZUGQGK5LE6787OhZ1JI9VPCL2Xxpps6Da+SGuSQG2Mo8z1DiEMRF58WIp9jDp5JPdOc/FK64kJ1hLye4c6U13V/6HFz9HI/Tk78WgjLN9ssj7FDpI+FlexYfoyJTQuWciMLhyXSGVN6X6500jtt9MhT0fgwa1/bY3LjESe9Pg+4mRnoAQfAr0NKuqTyNiDmCfribVujgomvi85MA8shx8pu8a8MWwwIwYJKoZIhvcNAQkVMRYEFK0PLPU1F5US4ZJUSUDLgYethBdOMEUGCSqGSIb3DQEJFDE4HjYAUwB1AHIAZwBlACAARwBlAG4AZQByAGEAdABlAGQAIABDAEEAIAAxADUARgA1ADAAOQAyAEIwLTAhMAkGBSsOAwIaBQAEFGM/Au5Qi2LRTTo4/ZHOg1ZpX4NQBAiGa0Oo8EoenA==

**Comment by ConnersHua** [comment]
为什么你 [URL Rewrite] 下有关去广告的格式都不正常的？Surge 3 具体是什么版本的？

**Comment by renjie45** [comment]
surge的版本是3.5.0(Build 1257) IOS是12.1.3 我直用的README.md页面上提供的surge3的捷径安装的https://www.icloud.com/shortcuts/8a2c2c9649dd484eab2f7e727282732c
然后捷径里就添加了我自己的节点信息,导入后就是上面的内容了.

**Comment by ConnersHua** [comment]
这个问题有点奇怪，我还在找

**Comment by touzi** [comment]
我也遇到了同样的问题, 捷径导入的很多 mitm 都不能解析出来.
