### ISSUE TITLE
请增加一条支持wolframalpha的规则

### ISSUE THREAD

**Issue by ceadmond** [ConnersHua/Profiles#62]
DOMAIN-SUFFIX,wolframalpha.com,PROXY

**Comment by ConnersHua** [comment]
完成

**Comment by ceadmond** [comment]
你最新的surge 2的规则里面，关于Akamai的四条规则前面是多打了#  了啊，这样规则应该就没法正常使用了吧。

Conners Hua <notifications@github.com> 于 2019年2月15日周五 下午10:05写道：

**Comment by ConnersHua** [comment]
那个是预留的，有些 CDN 的部分我还没确定所以暂时不启用
