### ISSUE TITLE
打不开微信公众号

### ISSUE THREAD

**Issue by nicedayever** [ConnersHua/Profiles#63]
Shadowrocket ，使用如下规则
https://github.com/ConnersHua/Profiles/blob/master/Shadow/Pro.conf
时间2019.02.13,
 打不开朋友圈的微信公众号文章，但是可以通过订阅号打开。

**Comment by ConnersHua** [comment]
无法复现，在「数据」>「日子」>「代理」中开启日志查看是怎么处理的吧

**Comment by BenjaminGao** [comment]
没发现这个情况

**Comment by nicedayever** [comment]
解决了，是Shadowrocket TF 版本BUG，App Store版本正常
