### ISSUE TITLE
使用 TOMTOM 地图数据的问题

### ISSUE THREAD

**Issue by luzhaohui** [ConnersHua/Profiles#71]
在 Profiles/Surge/Apple.list 中，将 gspe1-ssl.ls.apple.com 分流走代理，在 macOS 地图中确实会用 TOMTOM 数据，但在 iOS 地图中仍然会用 高德地图 数据。不知何故？

# > Apple News and Apple Map TOMTOM Version
**DOMAIN,gspe1-ssl.ls.apple.com**
PROCESS-NAME,News
USER-AGENT,AppleNews*

**Comment by ConnersHua** [comment]
新 iOS 地图不受 `gspe1-ssl.ls.apple.com` 影响了所以不会是 TOMTOM 数据

**Comment by luzhaohui** [comment]
好吧
