### ISSUE TITLE
Clash配置中的DNS问题

### ISSUE THREAD

**Issue by 3andero** [ConnersHua/Profiles#72]
Clash for Windows 客户端最新版本。
观察到非常奇怪的现象：使用校园网WIFI的时候，Global和Direct都符合预期，Rule模式下所有网站都无法访问，没有改动过规则的细节，只是加入了自己的服务器信息，全都是Vmess协议。
经过测试，把和DNS相关的所有东西都删掉，恢复正常。
其他的WIFI没有观察到类似的情况。

**Comment by ConnersHua** [comment]
将 DNS 配置部分注释后可正常使用？如使用 DNS 设置，连 HTTP 网址也上不去么？

**Comment by ConnersHua** [comment]
我在 Clash 的群里看到有讨论：

> 总结下CFW的DNS服务：
> 1. 必须把config里的dns所有内容全移到profiles里（config里不留DNS配置）。
> 2. DNS Server要写成纯IP（数字）

**Comment by 3andero** [comment]
抱歉，刚刚升级了最新版本的Clash for Windows (0.5.27), 无法再复现这个问题了。
