### ISSUE TITLE
SURGE PRO

### ISSUE THREAD

**Issue by tommychi018** [ConnersHua/Profiles#74]

**Comment by tommychi018** [comment]
SURGE PRO 无法打开微信的附件 如图， 需要验证 ，请大神帮忙，谢谢

![IMG_1257](https://user-images.githubusercontent.com/48246947/54201933-dd387e00-4509-11e9-8bc8-c7bc45fabb00.png)
![IMG_1258](https://user-images.githubusercontent.com/48246947/54201942-e32e5f00-4509-11e9-9674-1cf187d1bf83.png)

**Comment by ConnersHua** [comment]
> 如果使用了专业版规则并且开启了「HTTPS 解密(MitM)」功能不仅需要安装证书，还需在系统「设置」>「通用」>「关于本机」中底部的「证书信任设置」中信任所安装的证书

**Comment by tommychi018** [comment]
谢谢回复， 我试一下，。但证书有没有更新的， 哪里有下载？

**Comment by tommychi018** [comment]
试了，一切正常
