### ISSUE TITLE
Supercell 规则导致HTTPS代理无法连上Brawlstars

### ISSUE THREAD

**Issue by maxduke** [ConnersHua/Profiles#76]
Supercell Brawlstars的规则会导致 不支持udp的代理（如HTTPS代理）连接不上
# > Supercell
DOMAIN-SUFFIX,brawlstars.com
DOMAIN-SUFFIX,brawlstarsgame.com
DOMAIN-SUFFIX,supercell.com

建议这部分规则不要放到list中，可以自定义

**Comment by ConnersHua** [comment]
将自定义规则放置在最顶部即可覆盖

**Comment by maxduke** [comment]
多谢回复，有个建议，类似这些规则可以分开list，被qiang的和可加速的分开。再次感谢维护规则。

**Comment by ConnersHua** [comment]
有这个考虑，打算把可选是否代理的（如 OneDrive）做个策略组取代现在的黑白名单模式开关
