### ISSUE TITLE
招商系应用规则提交

### ISSUE THREAD

**Issue by destincc** [ConnersHua/Profiles#77]
DOMAIN-SUFFIX,amap.com,DIRECT
DOMAIN-SUFFIX,baidu.com,DIRECT
DOMAIN-SUFFIX,cmbimg.com,DIRECT
DOMAIN-SUFFIX,cmbchina.com,DIRECT

**Comment by destincc** [comment]
再加一条 也是招行的DOMAIN-SUFFIX,cmbimg.com,DIRECT

**Comment by nixilin** [comment]
招商系还包含了baidu.com和amap.com？    要不考虑用user-agent匹配吧。

**Comment by destincc** [comment]
> 招商系还包含了baidu.com和amap.com？    要不考虑用user-agent匹配吧。

我之前考虑到用到ua，但是你自己用surge看的话这两个的ua并不是招商，而且有时候用网页看的话也就不如这样直接匹配
