### ISSUE TITLE
小火箭使用神机规则导致掌上生活app无法联网

### ISSUE THREAD

**Issue by Andjustsoso** [ConnersHua/Profiles#85]
最新的测试版小火箭使用神机规则，会导致招行的掌上生活app无法连接网络，但是使用小火箭自带的规则就没有这个问题
使用quantumult配置神机规则也没有这个问题
所以我不清楚是小火箭的神机规则问题还是小火箭问题，只好全都报告一下，希望开发者能排除一下，谢谢

**Comment by ConnersHua** [comment]
2.1.24(90)？有开 MitM 么？

**Comment by Andjustsoso** [comment]
版本2.1.24（690），有开Mitm

**Comment by Andjustsoso** [comment]
> 2.1.24(90)？有开 MitM 么？

版本2.1.24（690），有开Mitm

**Comment by Andjustsoso** [comment]
关了mitm之后正常

**Comment by Andjustsoso** [comment]
搞定了，app作者修复了
