### ISSUE TITLE
添加 追书神器 复写

### ISSUE THREAD

**Issue by maxduke** [ConnersHua/Profiles#86]
# > 追书神器
^https?:\/\/api\.zhuishushenqi\.com\/advert - reject
^https?:\/\/api\.zhuishushenqi\.com\/notification\/shelfMessage - reject
^https?:\/\/api\.zhuishushenqi\.com\/recommend - reject
^https?:\/\/api\.zhuishushenqi\.com\/splashes\/ios - reject
^https?:\/\/mi\.gdt\.qq\.com\/gdt_mview\.fcg - reject
^https?:\/\/api\.zhuishushenqi\.com\/user\/bookshelf-updated - reject
^https?:\/\/itunes\.apple\.com\/lookup\?id=575826903 - reject

**Comment by ConnersHua** [comment]
`^https?://itunes.apple.com/lookup?id=575826903 - reject`
的作用是什么？

**Comment by maxduke** [comment]
之前某版本好像会有store的请求，可以先不加最后这条。

**Comment by ydzydzydz** [comment]
> `^https?://itunes.apple.com/lookup?id=575826903 - reject`
> 的作用是什么？

好像可以去掉追书神器弹出更新提醒
