### ISSUE TITLE
完善Spotify的代理规则

### ISSUE THREAD

**Issue by ceadmond** [ConnersHua/Profiles#87]
FINAL: [com.spotify.music] TCP new connection from 10.1.2.3:44143 -> 240.1.0.60(audio-sp-sjc.pscdn.co):443 redirect to custom proxy: 🇭🇰 HKBN
根据此条来自Surfboard的Logcat，可增加一条规则，DOMAIN-SUFFIX,pscdn.co,ForeignMedia

**Comment by ConnersHua** [comment]
感谢，已加
