### ISSUE TITLE
20190327 更新 surge 3.conf 及surge 2.conf

### ISSUE THREAD

**Issue by tommychi018** [ConnersHua/Profiles#92]
大佬， 1）我比较你03/27之前的surge 2 或3 conf , 配置， 发现VOA app（美国之音）现在开始打不开了（见图），导入你03/15 日的conf ,又可以了， 是否与更新Global List 有关， 或您更改了MITM 有关？ 是否我要增加一条DOMAIN-SUFFIX, voa.com, proxy 在RULESET/global list 

![IMG_2471](https://user-images.githubusercontent.com/48246947/55154921-f93a5180-5190-11e9-979f-7daa151ad19f.PNG)

2）下图的错误提示 我用在SURGE 3 IOS 从昨天开始出现？ ''socket closed by remote peer '' 请指点，谢谢
![IMG_1263](https://user-images.githubusercontent.com/48246947/55154926-fb041500-5190-11e9-8846-6292698d1b47.PNG)

**Comment by ConnersHua** [comment]
已修
