### ISSUE TITLE
telegram.list写在Global下面不会生效

### ISSUE THREAD

**Issue by TingoLee** [ConnersHua/Profiles#95]
telegram.list想给一个别的策略组，每次都匹配到Global上

**Comment by TingoLee** [comment]
surge3 ios

**Comment by ConnersHua** [comment]
感谢反馈，已修

**Comment by TingoLee** [comment]
好像还是不行，建议把global.list放在下边，按顺序还是会先匹配到global

**Comment by ConnersHua** [comment]
手动更新 Global.list

**Comment by Mrvivi** [comment]
其实我比较小白 甚至不知道怎么手动更新 Global.list


2019年4月10日 +0800 PM9:32 Conners Hua <notifications@github.com>，写道：

**Comment by TingoLee** [comment]
好了，谢谢
