### ISSUE TITLE
Apple News LIst 为什么要输入两次 DOMAIN ,gateway.icloud.com， PROXY?

### ISSUE THREAD

**Issue by tommychi018** [ConnersHua/Profiles#96]
请问大佬 ， 第一：为什么要输入两次 DOMAIN ,gateway.icloud.com， PROXY?
第二， 你在你的博客写  DOMAIN,gateway.icloud.com,PROXY 可能会造成其他问题， 为什么还在你的apple news list里面？

<img width="975" alt="Screen Shot 2019-04-11 at 10 26 45 AM" src="https://user-images.githubusercontent.com/48246947/55926561-64c9f780-5c44-11e9-8e48-c86c37af076d.png">

**Comment by ConnersHua** [comment]
加井号是注释，不启作用
