### ISSUE TITLE
神机大佬，能不能在ruleset/media中的HBO.list添加几条HBOGOHK的规则

### ISSUE THREAD

**Issue by wssXzzzz** [ConnersHua/Profiles#97]
例如
DOMAIN-SUFFIX,hboasia.com
DOMAIN-SUFFIX,hbogo.com
DOMAIN-SUFFIX,hbogoasia.hk

谢谢，感激不尽 如果有单独的hbohk的规则我没找到，请恕我打扰了

**Comment by xingkaixin** [comment]
你这里把HBO的代理新增一个名称，然后再Proxy Group对应添加就可以了呀。

**Comment by ConnersHua** [comment]
已经加到 HBO.list 中
